name: riverpod_tamplates
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter 

  cupertino_icons:
  # core_kit:
  #   path: C:/Users/kmmuz/Documents/flutter_project/flutter_core_kit

  core_kit:
    git:
      url: https://github.com/kmmuzahid/flutter_core_kit.git
      ref: 1.0.54  # Check releases for latest version

  flutter_riverpod:
  auto_route:
  flutter_secure_storage: 

dev_dependencies:
  flutter_test:
    sdk: flutter
  core_kit_lints:
    path: ../flutter_core_kit/tools/custom_lint
  flutter_lints: 

  build_runner:
  auto_route_generator:
  flutter_gen_runner:   
    
  flutter_launcher_icons:  
  intl_utils:  
  flutter_auto_size_text:
  pin_code_fields:
  change_app_package_name:

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/nav/
